fish_add_path -g ~/projects/go-workspace/bin/
fish_add_path -g /usr/local/sbin 
fish_add_path -g /sbin 
fish_add_path -g /opt/homebrew/opt/coreutils/libexec/gnubin
fish_add_path -g /opt/homebrew/share/google-cloud-sdk/bin/
fish_add_path -g ~/go/bin 
fish_add_path -g /opt/homebrew/bin
fish_add_path -g ~/configs/scripts
fish_add_path -g ~/.docker/bin/
fish_add_path -g /opt/homebrew/opt/mysql-client/bin/
